services:
    App\DataFixtures\:
        resource: '../src/DataFixtures/'

    App\Factory\:
        resource: '../src/Factory/'

    App\Shared\Twig\CspNonceStubExtension:
        tags: ['twig.extension']
